### ISSUE TITLE
关于webview的please renew

### ISSUE THREAD

**Issue by 1421794494** [aSurgingRiver/WebView#9]
![51BB3B89-69E7-4335-8342-E9B7C47A0377](https://user-images.githubusercontent.com/51696771/162556052-24f2ea01-5c9d-42f4-8dff-046ffbd5434f.png)
插件在使用一段时间后  webview左下角会显示以上红字信息

**Comment by 1421794494** [comment]
我非常确定是webview控件的问题，当我试图删除webview红字将消失

**Comment by aSurgingRiver** [comment]
你好，出现红色的字是正常的。说明你使用的授权文件已经过期，需要更新授权文件。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月09日 16:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) |

我非常确定是webview控件的问题，当我试图删除webview红字将消失

**Comment by 1421794494** [comment]
> 你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年04月09日 16:50 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

那我应该如何操作呢，重新下载插件到自己的ue4工程吗

**Comment by aSurgingRiver** [comment]
早期版本直接下载插件，最近下载的版本需要更新项目content/license目录下的授权文件



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月09日 18:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) |

你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 16:50 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

那我应该如何操作呢，重新下载插件到自己的ue4工程吗

**Comment by 1421794494** [comment]
> 早期版本直接下载插件，最近下载的版本需要更新项目content/license目录下的授权文件
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年04月09日 18:15 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 16:50 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 那我应该如何操作呢，重新下载插件到自己的ue4工程吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我使用的是4.26版本，并未在插件目录下content下找到license文件夹，是我操作的不对吗

**Comment by aSurgingRiver** [comment]
说明你使用的是早期版本，可以直接下载最新的插件即可



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月09日 18:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) |

早期版本直接下载插件，最近下载的版本需要更新项目content/license目录下的授权文件
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 18:15 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 16:50 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 那我应该如何操作呢，重新下载插件到自己的ue4工程吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

我使用的是4.26版本，并未在插件目录下content下找到license文件夹，是我操作的不对吗

**Comment by 1421794494** [comment]
> 说明你使用的是早期版本，可以直接下载最新的插件即可
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年04月09日 18:28 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 早期版本直接下载插件，最近下载的版本需要更新项目content/license目录下的授权文件 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 18:15 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 16:50 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 那我应该如何操作呢，重新下载插件到自己的ue4工程吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 我使用的是4.26版本，并未在插件目录下content下找到license文件夹，是我操作的不对吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

非常感谢您为我耐心的解答，我稍后将去尝试将插件更新至最新的版本，我还有一点不解的地方，关于授权文件，它会在使用一段时间后再次出现在我的屏幕上吗？我将要在我的打包程序中使用它 我不是特别希望它的出现

**Comment by aSurgingRiver** [comment]
https://www.zhihu.com/column/c_1490114276946223104
关于授权文件请查看这里面关于license章节



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月09日 18:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) |

说明你使用的是早期版本，可以直接下载最新的插件即可
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 18:28 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 早期版本直接下载插件，最近下载的版本需要更新项目content/license目录下的授权文件 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 18:15 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 你好，出现红色的字是正常的。说明你使用的授权文件已经过渡，需要更新授权文件。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年04月09日 16:50 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [aSurgingRiver/WebView] 关于webview的please renew (Issue #9) | 我非常确定是webview控件的问题，当我试图删除webview红字将消失 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 那我应该如何操作呢，重新下载插件到自己的ue4工程吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 我使用的是4.26版本，并未在插件目录下content下找到license文件夹，是我操作的不对吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

非常感谢您为我耐心的解答，我稍后将去尝试将插件更新至最新的版本，我还有一点不解的地方，关于授权文件，它会在使用一段时间后再次出现在我的屏幕上吗？我将要在我的打包程序中使用它 我不是特别希望它的出现
